# Generated by Django 2.1.7 on 2019-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateTimeField(verbose_name='Date of Day')),
            ],
        ),
        migrations.CreateModel(
            name='SingleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Start Date')),
                ('endTime', models.DateTimeField(verbose_name='End Date')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sleep', 'SLEEP'), ('academics', 'ACADEMICS'), ('leisure', 'LEISURE'), ('mentalhealth', 'MENTAL HEALTH'), ('personaldevelopment', 'PERSONAL DEVELOPMENT'), ('professionaldevelopment', 'PROFESSIONAL DEVELOPMENT'), ('operational', 'OPERATIONAL'), ('excercise', 'EXCERCISE'), ('health', 'HEALTH')], max_length=50)),
            ],
        ),
    ]
