# Generated by Django 2.2.7 on 2019-11-15 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField(verbose_name='Date of Day')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Sleep', 'SLEEP'), ('Academics', 'ACADEMICS'), ('Leisure', 'LEISURE'), ('Mental Health', 'MENTAL HEALTH'), ('Personal Development', 'PERSONAL DEVELOPMENT'), ('Professional Development', 'PROFESSIONAL DEVELOPMENT'), ('Operational', 'OPERATIONAL'), ('Excercise', 'EXCERCISE'), ('Health', 'HEALTH')], max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.Day')),
            ],
        ),
    ]
