# Generated by Django 2.1.7 on 2019-10-29 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleentry',
            name='day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logbook.DailyLog'),
            preserve_default=False,
        ),
    ]
