# Generated by Django 2.2.7 on 2019-11-15 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 15, 15, 35, 648205)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 15, 15, 35, 648177)),
        ),
    ]
