# Generated by Django 2.1.7 on 2019-10-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_singleentry_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='entryDate',
            field=models.DateField(verbose_name='Date of Day'),
        ),
    ]
