# Generated by Django 2.1.7 on 2019-11-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20191030_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingleEntry',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='DailyLog',
            new_name='Day',
        ),
    ]

    atomic = False
