# Generated by Django 2.1.7 on 2019-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_auto_20191101_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
    ]
