# Generated by Django 2.1.7 on 2019-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_auto_20191101_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
