# Generated by Django 2.1.7 on 2019-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_auto_20191101_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.TextField(),
        ),
    ]
