# Generated by Django 2.1.7 on 2019-11-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_auto_20191101_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.CharField(max_length=200),
        ),
    ]
