# Generated by Django 2.1.7 on 2019-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_auto_20191101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
