# Generated by Django 2.1.7 on 2019-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0014_auto_20191101_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Sleep', 'SLEEP'), ('Academics', 'ACADEMICS'), ('Leisure', 'LEISURE'), ('Mental Health', 'MENTAL HEALTH'), ('Personal Development', 'PERSONAL DEVELOPMENT'), ('Professional Development', 'PROFESSIONAL DEVELOPMENT'), ('Operational', 'OPERATIONAL'), ('Excercise', 'EXCERCISE'), ('Health', 'HEALTH')], max_length=50),
        ),
    ]
